#pragma once
#include <iostream>

void hello();
void simpleAdder();
void betweenAdder();
void StringIO();
void q1_1();
void FunctionOverloading();
void q1_2();
void DefaultValue1();
void DefaultValue2();
void DefaultValue3();
void InlineFunc();
void NameSp1();
void NameSp2();
void NameSp3();
void UsingDcl1();
void UsingDcl2();
void UsingDcl3();
void NameAlias();
void TrueAndFalse();
void DataTypeBool();
void Referen();
void RefSwap();